### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by captainredbleach** [adafruit/Adafruit_HMC5883_Unified#5]
Need help to fix this problem.
The file "magsensor.ino" exists and so does the file "Adafruit_Sensor.h"

Here is the console log for the problem
-------
C:\Users\Administrator\Desktop\Adafruit_HMC5883_Unified-master\examples\magsensor\magsensor.ino:33:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by ladyada** [comment]
install https://github.com/adafruit/Adafruit_Sensor
